export const POSITION = 'POSITION'
export const BOUNDS = 'BOUNDS'
export const POKELIST = 'POKELIST'
export const AUTHTOKEN = 'AUTHTOKEN'
export const POKEDEX = 'POKEDEX'
export const LOGIN_PASSED = 'LOGIN_PASSED'
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE'
export const IS_NIGHT = 'IS_NIGHT'
export const HISTORY = 'HISTORY'

